### ISSUE TITLE
UI theme and animations

### ISSUE THREAD

**Issue by dejan-xd** [dejan-xd/Game_Engine_MBRS#22]
Potrebno je promeniti izgled UI i ubaciti animacije kako bi izgled prozora bio lepši. Za realizovanje ovog taska potrebno je dodati Color Pallete sa bojama koje će se koristiti unutar aplikacije. Tu paletu možemo kasnije proširivati. Takođe je potrebno kreirati stilove za sve komponente wpf prozora kako ne bi morali svaki put iznova da se piše izgled za iste komponente.
Što se tiče animacija, potrebno je ubaciti jednu od easing funkcija.
Preporuka je da tema bude tamnija radi prirode ljudskog oka i razlikovanja boja.

**Comment by jovan92** [comment]
Ovaj issue je zatvoren sa #24
