### ISSUE TITLE
Hosting a Win32 window in WPF

### ISSUE THREAD

**Issue by dejan-xd** [dejan-xd/Game_Engine_MBRS#61]
Potrebno je koristiti HwndHost klasu da se hostuje Win32 prozor unutar samog GameEngine editora.

Hosting Win32 Content in WPF:
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/hosting-win32-content-in-wpf?view=netframeworkdesktop-4.8

Walkthrough: Host a Win32 Control in WPF:
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-hosting-a-win32-control-in-wpf?view=netframeworkdesktop-4.8

**Comment by nole23** [comment]
Odradjeno kroz feature #62
